#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage: $(basename "$0") --repo-name <name> [--check]

Options:
  --repo-name <name>  Consumer name under repos/ (e.g., my-repo)
  --check             Verify generated output matches target repo without writing
USAGE
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

REPO_NAME=""
CHECK_ONLY=0

while (($# > 0)); do
  case "$1" in
    --repo-name)
      REPO_NAME="${2:-}"
      shift 2
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$REPO_NAME" ]]; then
  echo "--repo-name is required" >&2
  usage >&2
  exit 2
fi

REPO_DIR="$ROOT_DIR/repos/$REPO_NAME"
OVERLAY_DIR="$REPO_DIR/overlay"
REPO_PATH_FILE="$REPO_DIR/repo.path"

if [[ ! -f "$REPO_PATH_FILE" ]]; then
  echo "Missing repo path file: $REPO_PATH_FILE" >&2
  exit 1
fi

TARGET_REPO=$(<"$REPO_PATH_FILE")
if [[ ! -d "$TARGET_REPO" ]]; then
  echo "Target repo does not exist: $TARGET_REPO" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d)
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

mkdir -p "$TMP_DIR/skills"

prepend_generated_header() {
  local src="$1"
  local dst="$2"
  {
    echo "<!-- GENERATED BY scripts/sync-repo.sh for ${REPO_NAME}. DO NOT EDIT DIRECTLY. -->"
    echo
    cat "$src"
  } > "$dst"
}

render_root_file() {
  local target_name="$1"  # AGENTS or CLAUDE
  local core_file="$ROOT_DIR/core/${target_name}.core.md"
  local overlay_full="$OVERLAY_DIR/${target_name}.full.md"
  local overlay_append="$OVERLAY_DIR/${target_name}.append.md"
  local out="$TMP_DIR/${target_name}.md"

  if [[ -f "$overlay_full" ]]; then
    prepend_generated_header "$overlay_full" "$out"
    return
  fi

  if [[ ! -f "$core_file" ]]; then
    echo "Missing core file: $core_file" >&2
    exit 1
  fi

  if [[ -f "$overlay_append" ]]; then
    {
      cat "$core_file"
      echo
      cat "$overlay_append"
    } > "$TMP_DIR/${target_name}.body.md"
    prepend_generated_header "$TMP_DIR/${target_name}.body.md" "$out"
  else
    prepend_generated_header "$core_file" "$out"
  fi
}

render_skill_files() {
  local core_skills_dir="$ROOT_DIR/core/skills"
  local overlay_skills_dir="$OVERLAY_DIR/skills"

  if [[ ! -d "$core_skills_dir" ]]; then
    echo "Missing core skills dir: $core_skills_dir" >&2
    exit 1
  fi

  while IFS= read -r src; do
    rel="${src#$core_skills_dir/}"
    out="$TMP_DIR/skills/$rel"
    mkdir -p "$(dirname "$out")"
    prepend_generated_header "$src" "$out"
  done < <(find "$core_skills_dir" -type f | sort)

  if [[ -d "$overlay_skills_dir" ]]; then
    while IFS= read -r src; do
      rel="${src#$overlay_skills_dir/}"
      out="$TMP_DIR/skills/$rel"
      mkdir -p "$(dirname "$out")"
      prepend_generated_header "$src" "$out"
    done < <(find "$overlay_skills_dir" -type f | sort)
  fi
}

render_root_file "AGENTS"
# CLAUDE.md intentionally mirrors AGENTS.md exactly across all repos.
cp "$TMP_DIR/AGENTS.md" "$TMP_DIR/CLAUDE.md"
render_skill_files

if ((CHECK_ONLY == 1)); then
  diff_failed=0

  if ! diff -u "$TARGET_REPO/AGENTS.md" "$TMP_DIR/AGENTS.md" >/dev/null 2>&1; then
    echo "AGENTS.md differs for $REPO_NAME"
    diff_failed=1
  fi
  if ! diff -u "$TARGET_REPO/CLAUDE.md" "$TMP_DIR/CLAUDE.md" >/dev/null 2>&1; then
    echo "CLAUDE.md differs for $REPO_NAME"
    diff_failed=1
  fi

  while IFS= read -r gen_skill; do
    rel="${gen_skill#$TMP_DIR/skills/}"
    if ! diff -u "$TARGET_REPO/skills/$rel" "$gen_skill" >/dev/null 2>&1; then
      echo "skills/$rel differs for $REPO_NAME"
      diff_failed=1
    fi
  done < <(find "$TMP_DIR/skills" -type f | sort)

  if ((diff_failed == 1)); then
    exit 1
  fi

  echo "OK: $REPO_NAME is in sync"
  exit 0
fi

cp "$TMP_DIR/AGENTS.md" "$TARGET_REPO/AGENTS.md"
cp "$TMP_DIR/CLAUDE.md" "$TARGET_REPO/CLAUDE.md"
mkdir -p "$TARGET_REPO/skills"
while IFS= read -r gen_skill; do
  rel="${gen_skill#$TMP_DIR/skills/}"
  out="$TARGET_REPO/skills/$rel"
  mkdir -p "$(dirname "$out")"
  cp "$gen_skill" "$out"
done < <(find "$TMP_DIR/skills" -type f | sort)

# Hard-cut migration: remove previously generated rule files.
legacy_rules=(
  create-prd.md
  create-tdd.md
  generate-tasks.md
  improve-plan.md
  socratic-planning.md
  task-management.md
)
for rule_file in "${legacy_rules[@]}"; do
  rm -f "$TARGET_REPO/rules/$rule_file"
done
rmdir "$TARGET_REPO/rules" >/dev/null 2>&1 || true

echo "Synced: $REPO_NAME -> $TARGET_REPO"
