#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage: $(basename "$0") --repo-name <name> [--check]

Options:
  --repo-name <name>  Consumer name under repos/ (e.g., autoprophet, sortinghat)
  --check             Verify generated output matches target repo without writing
USAGE
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT_DIR=$(cd "$SCRIPT_DIR/.." && pwd)

REPO_NAME=""
CHECK_ONLY=0

while (($# > 0)); do
  case "$1" in
    --repo-name)
      REPO_NAME="${2:-}"
      shift 2
      ;;
    --check)
      CHECK_ONLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown arg: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$REPO_NAME" ]]; then
  echo "--repo-name is required" >&2
  usage >&2
  exit 2
fi

REPO_DIR="$ROOT_DIR/repos/$REPO_NAME"
OVERLAY_DIR="$REPO_DIR/overlay"
REPO_PATH_FILE="$REPO_DIR/repo.path"

if [[ ! -f "$REPO_PATH_FILE" ]]; then
  echo "Missing repo path file: $REPO_PATH_FILE" >&2
  exit 1
fi

TARGET_REPO=$(<"$REPO_PATH_FILE")
if [[ ! -d "$TARGET_REPO" ]]; then
  echo "Target repo does not exist: $TARGET_REPO" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d)
cleanup() { rm -rf "$TMP_DIR"; }
trap cleanup EXIT

mkdir -p "$TMP_DIR/rules"

prepend_generated_header() {
  local src="$1"
  local dst="$2"
  {
    echo "<!-- GENERATED BY primedirective/scripts/sync-repo.sh for ${REPO_NAME}. DO NOT EDIT DIRECTLY. -->"
    echo
    cat "$src"
  } > "$dst"
}

render_root_file() {
  local target_name="$1"  # AGENTS or CLAUDE
  local core_file="$ROOT_DIR/core/${target_name}.core.md"
  local overlay_full="$OVERLAY_DIR/${target_name}.full.md"
  local overlay_append="$OVERLAY_DIR/${target_name}.append.md"
  local out="$TMP_DIR/${target_name}.md"

  if [[ -f "$overlay_full" ]]; then
    prepend_generated_header "$overlay_full" "$out"
    return
  fi

  if [[ ! -f "$core_file" ]]; then
    echo "Missing core file: $core_file" >&2
    exit 1
  fi

  if [[ -f "$overlay_append" ]]; then
    {
      cat "$core_file"
      echo
      cat "$overlay_append"
    } > "$TMP_DIR/${target_name}.body.md"
    prepend_generated_header "$TMP_DIR/${target_name}.body.md" "$out"
  else
    prepend_generated_header "$core_file" "$out"
  fi
}

render_rule_file() {
  local base
  base=$(basename "$1")
  local overlay_rule="$OVERLAY_DIR/rules/$base"

  if [[ -f "$overlay_rule" ]]; then
    prepend_generated_header "$overlay_rule" "$TMP_DIR/rules/$base"
  else
    prepend_generated_header "$1" "$TMP_DIR/rules/$base"
  fi
}

render_root_file "AGENTS"
render_root_file "CLAUDE"

for core_rule in "$ROOT_DIR"/core/rules/*.md; do
  render_rule_file "$core_rule"
done

if ((CHECK_ONLY == 1)); then
  diff_failed=0

  if ! diff -u "$TARGET_REPO/AGENTS.md" "$TMP_DIR/AGENTS.md" >/dev/null 2>&1; then
    echo "AGENTS.md differs for $REPO_NAME"
    diff_failed=1
  fi
  if ! diff -u "$TARGET_REPO/CLAUDE.md" "$TMP_DIR/CLAUDE.md" >/dev/null 2>&1; then
    echo "CLAUDE.md differs for $REPO_NAME"
    diff_failed=1
  fi

  while IFS= read -r gen_rule; do
    rel="rules/$(basename "$gen_rule")"
    if ! diff -u "$TARGET_REPO/$rel" "$gen_rule" >/dev/null 2>&1; then
      echo "$rel differs for $REPO_NAME"
      diff_failed=1
    fi
  done < <(find "$TMP_DIR/rules" -type f | sort)

  if ((diff_failed == 1)); then
    exit 1
  fi

  echo "OK: $REPO_NAME is in sync"
  exit 0
fi

mkdir -p "$TARGET_REPO/rules"
cp "$TMP_DIR/AGENTS.md" "$TARGET_REPO/AGENTS.md"
cp "$TMP_DIR/CLAUDE.md" "$TARGET_REPO/CLAUDE.md"
cp "$TMP_DIR"/rules/*.md "$TARGET_REPO/rules/"

echo "Synced: $REPO_NAME -> $TARGET_REPO"
